---
title: Classe Stellare
timezone: Europe/Rome
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
image: "/uploads/boy.jpg"

theme: jekyll-theme-tactile